### ISSUE TITLE
(docs) Best Practice Example for self-updating bork

### ISSUE THREAD

**Issue by lucymhdavies** [skylarmacdonald/bork#30]
Readme has instructions for installing from source, and with brew.

We should come up with some examples for having bork update itself.

**Comment by lucymhdavies** [comment]
@skylarmacdonald 's example:

https://github.com/skylarmacdonald/dotfiles/blob/main/bork/_init_mac.sh#L33-L38

Should work _if_ you have permission to create the directory, but not so much if you can't

```
$ mkdir /usr/local/src
mkdir: /usr/local/src: Permission denied
```

If brew is available on your system, then the following works a treat:

```
ok brew bork
```

But relies on figuring out the correct process for releasing (and potentially automating) new Brew releases.


Or, if you want the absolute latest from head, you can install with brew like so:

```
brew install bork --HEAD --fetch-HEAD
```

but convincing Bork to keep itself up-to-date when installed by that method currently perplexes me.

**Comment by skylarmacdonald** [comment]
The `brew` type can't currently fetch HEAD, and it will need to in order for Bork to self-update from HEAD like this. That's a [separate but related issue](https://github.com/skylarmacdonald/bork/issues/31) which will help to do what you're trying to achieve here.

Following our discussion I've thought it might be a good idea for `bork --version` to check if you've installed Bork via git, and if so, show you what branch you're on. This might help with update scripts.

I am not keen on having Bork update itself automatically, as I'd prefer the package managers to do that, but I'm happy for Bork to instruct the package managers to do that. :)

**Comment by lucymhdavies** [comment]
that `bork --version` enhancement would be good

And yeah, same, having something like this would be my preference:

```
ok brew bork --HEAD --fetch-HEAD
```

i.e. implementing https://github.com/skylarmacdonald/bork/issues/31

**Comment by skylarmacdonald** [comment]
I've added some instructions to the README in 9278636, so you should now be able to do this with `ok brew bork --HEAD`.
